In [37]:
import numpy as np

<div style="color: blue; font-family: 'david', sans-serif; font-size: 24px; font-weight: bold;">    question 1</div>

In [39]:
np.random.seed(80)
arr_rand = np.random.randint(1,100,(4,4))
print("- a- ",arr_rand[50<arr_rand])

- a-  [61 84 51 87 82 65 93]


In [57]:
col_sum = np.sum(arr_rand,axis=0)
row_sum = np.sum(arr_rand,axis=1)
print(arr_rand)
print("- b - column sum = ",col_sum)
print("- b - row sum = ",row_sum)

[[48 61 39 84]
 [11 51  4 87]
 [24 16 82  6]
 [65 10 93 43]]
- b - column sum =  [148 138 218 220]
- b - row sum =  [232 153 128 211]


In [97]:
print("-c- 1")
print("max col[0]",np.max(arr_rand[:,0]))
print("max col[1]",np.max(arr_rand[:,1]))
print("max col[2]",np.max(arr_rand[:,2]))
print("max col[3]",np.max(arr_rand[:,3]))
print("max row[0]",np.max(arr_rand[0,:]))
print("max row[1]",np.max(arr_rand[1,:]))
print("max row[2]",np.max(arr_rand[2,:]))
print("max row[3]",np.max(arr_rand[3,:]))

max col[0] 65
max col[1] 61
max col[2] 93
max col[3] 87
[65 61 93 87]
max row[0] 84
max row[1] 87
max row[2] 82
max row[3] 93


In [99]:
print("-c- 2")
print("min col[0]",np.min(arr_rand[:,0]))
print("min col[1]",np.min(arr_rand[:,1]))
print("min col[2]",np.min(arr_rand[:,2]))
print("min col[3]",np.min(arr_rand[:,3]))
print("min row[0]",np.min(arr_rand[0,:]))
print("min row[1]",np.min(arr_rand[1,:]))
print("min row[2]",np.min(arr_rand[2,:]))
print("min row[3]",np.min(arr_rand[3,:]))

-c- 1
min col[0] 11
min col[1] 10
min col[2] 4
min col[3] 6
min row[0] 39
min row[1] 4
min row[2] 6
min row[3] 10


In [121]:
print("-c- 3")
print("mean col[0]",np.mean(arr_rand[:,0]))
print("mean col[1]",np.mean(arr_rand[:,1]))
print("mean col[2]",np.mean(arr_rand[:,2]))
print("mean col[3]",np.mean(arr_rand[:,3]))
for i in arr_rand:
    print("mean row- ",np.mean(i))


-c- 3
mean col[0] 37.0
mean col[1] 34.5
mean col[2] 54.5
mean col[3] 55.0
mean row-  58.0
mean row-  38.25
mean row-  32.0
mean row-  52.75


<div style="color: blue; font-family: 'david', sans-serif; font-size: 24px; font-weight: bold;">    question 2- pandas</div>

In [125]:
import pandas as pd

In [143]:
new_games = {
"Final Fantasy VII Rebirth": 69.99,
"Astro Bot": 59.99,
"Star Wars Outlaws": 69.99,
"Silent Hill 2 Remake": 69.99,
"Elden Ring: Shadow of the Erdtree": 39.99,
"Dragon Age: The Veilguard": 69.99,
"Metaphor: ReFantazio": 59.99
}
games_ser= pd.Series(new_games)
print("- a -",games_ser["Metaphor: ReFantazio"])
print("- b -",list(games_ser.keys()))
print("- c -",games_ser.iloc[3])
print("- d -","the price of all games is moria: ",sum(games_ser.values))

- a - 59.99
- b - ['Final Fantasy VII Rebirth', 'Astro Bot', 'Star Wars Outlaws', 'Silent Hill 2 Remake', 'Elden Ring: Shadow of the Erdtree', 'Dragon Age: The Veilguard', 'Metaphor: ReFantazio']
- c - 69.99
- d - the price of all games is moria:  439.93
